name: Living Spec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install SpecFlow
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
    - name: Export Living Docs
      run:  livingdoc feature-folder features
    - name: Archive Living Docs
      uses: actions/upload-artifact@v3
      with:
        name: living-docs
        path: LivingDoc.html

