name: Living Spec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install SpecFlow
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
    - name: Export Living Docs
      run: |
        livingdoc feature-folder features
        mkdir github-pages
        mv LivingDoc.html github-pages/index.html
    - name: Archive Living Docs
      uses: actions/upload-artifact@v3
      with:
        name: living-docs
        path: github-pages/index.html

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fetch Living Docs from Artifacts
      uses: actions/download-artifact@v3
      with:
        name: living-doc
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: github-pages
